### ISSUE TITLE
Internet Archive link returns 404

### ISSUE THREAD

**Issue by emanueln** [opentimestamps/opentimestamps.org#33]
Tried to click the Internet Archive link on multiple devices, received 
404 Not Found from the nginx/1.10.3 (Ubuntu) server.

**Comment by RCasatta** [comment]
Thanks for reporting it, we fixed the error but at the moment the interface works but the ots are not downloaded, we are looking into the error

**Comment by philbertw4** [comment]
Wasn't sure whether to open a new issue or not, as this one is over a year old, but I just wanted to report that the Internet Archive link on the home page still doesn't seem to be working.
